apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  # These credentials will be used by both MongoDB and the Flask App
  mongo-root-username: admin
  mongo-root-password: password123
